import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Toaster } from 'sonner'
import { ThemeProvider } from '@/providers/ThemeProvider'
import Navbar from '@/components/Navbar'
import { AuthProvider } from '@/providers/AuthProvider'
import { EdgeStoreProvider } from '@/providers/edgestore'
import { ModalProvider } from '@/providers/ModalProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={`${inter.className} ${'theme-rose'}`}>
        <AuthProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <EdgeStoreProvider>
              <Navbar />
              {children}
              <Toaster
                toastOptions={{
                  unstyled: true,
                  classNames: {
                    error: 'bg-red-400',
                    success: 'text-green-400',
                    warning: 'text-yellow-400',
                    info: 'bg-blue-400',
                  },
                }}
              />
              <ModalProvider />
            </EdgeStoreProvider>
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
